### PR TITLE
Have your opacity and have it fast

### PR DESCRIPTION
**Pull request by coballast**
Got it working with the shader version.

### CODE REVIEW

**Comment by coballast** [comment]
I think I can get the displacement maps working too. It'll probably be much faster.

**Review by philipswan — APPROVED** [review]

**Comment by philipswan** [comment]
Merged Collin's variable tether opacity shader changes

**Comment by coballast** [comment]
This is for the earths opacity. It is not for the tethers. :)

**Comment by coballast** [comment]
I also discovered a few bugs afterwords. Sorry but we may want to consider undoing this commit.

**Pull request merged**
